id: P010709
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016284
  title: ཐུགས་རྗེ་ཆེན་པོ་སྤྱན་རས་གཟིགས་ངན་སོང་རང་གྲོལ་ཆོས་སྐོར།
  author: ''
  volumes:
    affe28e349964cb681cf00e6f111eeaa:
      image_group_id: I00JW501189
      title: ''
      volume_number: 1
      total_pages: 586
