id: P010709
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:56.484647
source_metadata:
  id: bdr:W00EGS1016284
  title: ཐུགས་རྗེ་ཆེན་པོ་སྤྱན་རས་གཟིགས་ངན་སོང་རང་གྲོལ་ཆོས་སྐོར།
  author: ''
  volumes:
    affe28e349964cb681cf00e6f111eeaa:
      image_group_id: I00JW501189
      title: ''
      volume_number: 1
      total_pages: 586
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
