id: I80808A28
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T14:10:20+00:00'
last_modified: '2022-06-08T16:58:00.036078+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016284
  title: ཐུགས་རྗེ་ཆེན་པོ་སྤྱན་རས་གཟིགས་ངན་སོང་རང་གྲོལ་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C51C:
      image_group_id: I00JW501189
      title: ''
      total_pages: 586
      order: 1
      base_file: C51C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
